execution:
    uuid: 778c0871-f9af-442e-b472-3b94fe0408a8
    runtime:
        start: 2017-06-16T10:49:26.155955-04:00
        end: 2017-06-16T10:49:26.355321-04:00
        duration: 199366 microseconds

action:
    type: import
    format: DNAFASTAFormat
    manifest:
    -   name: 97_otus_16S.fasta
        md5sum: d969a5a991b8e087bf0a0b9e1fb16066

environment:
    platform: linux-x86_64
    python: |-
        3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13)
        [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
    framework: 2017.6.0
    plugins: {}
    python-packages:
        q2-diversity: 2017.6.0
        traitlets: 4.3.2
        PyYAML: '3.12'
        wheel: 0.29.0
        html5lib: '0.999'
        scipy: 0.19.0
        pyparsing: 2.1.4
        future: 0.16.0
        six: 1.10.0
        cycler: 0.10.0
        q2-feature-table: 2017.6.0
        q2cli: 2017.6.0
        wcwidth: 0.1.7
        MarkupSafe: '0.23'
        CacheControl: 0.11.7
        mistune: 0.7.4
        bleach: 1.5.0
        nbformat: 4.3.0
        q2-demux: 2017.6.0
        deblur: 1.0.2
        scikit-bio: 0.5.1
        Pygments: 2.2.0
        numpy: 1.13.0
        tornado: 4.5.1
        q2-deblur: 2017.6.0
        bkcharts: '0.2'
        statsmodels: 0.8.0
        q2-composition: 2017.6.0
        lockfile: 0.12.2
        entrypoints: 0.2.2
        psutil: 5.2.2
        simplegeneric: 0.8.1
        testpath: '0.3'
        jupyter-client: 5.0.1
        q2-emperor: 2017.6.0
        ipywidgets: 6.0.0
        python-dateutil: 2.6.0
        q2templates: 2017.6.0
        patsy: 0.4.1
        q2-metadata: 2017.6.0
        jupyter-core: 4.3.0
        ipykernel: 4.6.1
        h5py: 2.7.0
        q2-types: 2017.6.0
        click: '6.7'
        decorator: 4.0.11
        pytz: '2017.2'
        q2-dada2: 2017.6.0
        bokeh: 0.12.6
        jsonschema: 2.6.0
        ptyprocess: 0.5.1
        pandas: 0.20.2
        matplotlib: 2.0.2
        requests: 2.14.2
        ipython-genutils: 0.2.0
        q2-alignment: 2017.6.0
        nbconvert: 5.2.1
        q2-taxa: 2017.6.0
        q2-feature-classifier: 2017.6.0
        terminado: '0.6'
        pickleshare: 0.7.4
        q2-quality-filter: 2017.6.0
        prompt-toolkit: 1.0.14
        q2-phylogeny: 2017.6.0
        natsort: 5.0.3
        qiime2: 2017.6.0
        seaborn: 0.7.1
        pip: 9.0.1
        pandocfilters: 1.4.1
        scikit-learn: 0.18.1
        notebook: 5.0.0
        pyzmq: 16.0.2
        emperor: 1.0.0b8
        widgetsnbextension: 2.0.0
        jedi: 0.10.2
        Jinja2: 2.9.6
        nose: 1.3.7
        pexpect: 4.2.1
        ipython: 6.1.0
        biom-format: 2.1.5
        ijson: '2.3'
        setuptools: 27.2.0
        tzlocal: '1.3'
